<?xml version="1.0"?>
<package format="3">
  <name>rtk2026_bringup</name>
  <version>0.1.0</version>
  <description>Launch файлы для запуска RTK2026</description>
  <maintainer email="todo@todo.com">rtk2026</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>rtk2026_driver</exec_depend>
  <exec_depend>rtk2026_odometry</exec_depend>
  <exec_depend>rtk2026_description</exec_depend>
  <exec_depend>slam_toolbox</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
