sim_encoder:
  ros__parameters:
    joint_states_topic: "/world/polygon_5x5_cells/model/rtk2026/joint_state"
    encoder_report_topic: "encoder_report"
    left_joint_name: "left_wheel_joint"
    right_joint_name: "right_wheel_joint"
    ticks_per_meter: 1268.0
    wheel_radius: 0.02585
    left_sign: 1
    right_sign: 1