FROM arm64v8/ros:jazzy

RUN apt-get update -o Acquire::Retries=5 && apt-get install -y --no-install-recommends --fix-missing \
    ros-jazzy-turtlebot3 \
    ros-jazzy-turtlebot3-simulations \
    ros-jazzy-ros-gz \
    ros-jazzy-ros-gz-sim \
    ros-jazzy-ros-gz-bridge \
    ros-jazzy-slam-toolbox \
    ros-jazzy-nav2-amcl \
    ros-jazzy-nav2-map-server \
    ros-jazzy-nav2-lifecycle-manager \
    ros-jazzy-nav2-costmap-2d \
    ros-jazzy-nav2-msgs \
    ros-jazzy-nav2-rviz-plugins \
    ros-jazzy-foxglove-bridge \
    ros-jazzy-teleop-twist-keyboard \
    python3-colcon-common-extensions \
    xvfb \
    x11vnc \
    fluxbox \
    novnc \
    websockify \
    && rm -rf /var/lib/apt/lists/*

ENV TURTLEBOT3_MODEL=burger
ENV LIBGL_ALWAYS_SOFTWARE=1
ENV GZ_SIM_RESOURCE_PATH=/opt/ros/jazzy/share/turtlebot3_gazebo/models:/workspace/worlds

WORKDIR /workspace

COPY docker/scripts /scripts
RUN chmod +x /scripts/*.sh

COPY src /workspace/src
RUN . /opt/ros/jazzy/setup.sh && colcon build --symlink-install