set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(TOOLCHAIN_DIR "${CMAKE_CURRENT_LIST_DIR}/../avr8-gnu-toolchain-win32_x86_64")
set(AVR_BIN_DIR "${TOOLCHAIN_DIR}/bin")

set(CMAKE_C_COMPILER "${AVR_BIN_DIR}/avr-gcc.exe" CACHE FILEPATH "" FORCE)
set(CMAKE_CXX_COMPILER "${AVR_BIN_DIR}/avr-g++.exe" CACHE FILEPATH "" FORCE)
set(CMAKE_ASM_COMPILER "${AVR_BIN_DIR}/avr-gcc.exe" CACHE FILEPATH "" FORCE)

set(CMAKE_FIND_ROOT_PATH "${TOOLCHAIN_DIR}" CACHE PATH "" FORCE)
