set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

find_program(AVR_GCC_PROGRAM NAMES avr-gcc REQUIRED)
find_program(AVR_GXX_PROGRAM NAMES avr-g++ REQUIRED)

set(CMAKE_C_COMPILER "${AVR_GCC_PROGRAM}" CACHE FILEPATH "" FORCE)
set(CMAKE_CXX_COMPILER "${AVR_GXX_PROGRAM}" CACHE FILEPATH "" FORCE)
set(CMAKE_ASM_COMPILER "${AVR_GCC_PROGRAM}" CACHE FILEPATH "" FORCE)
